import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';

const root = process.cwd();
const output = path.join(root, 'release/native');
const vendor = path.join(root, 'native/vendor/raylib-6.0_win64_mingw-w64');
fs.mkdirSync(path.join(output, 'runtime'), {recursive:true});
await build({entryPoints:['native/host.ts'], bundle:true, platform:'node', format:'cjs', outfile:path.join(output,'rules.cjs')});
fs.copyFileSync(process.execPath, path.join(output, 'runtime/node.exe'));
fs.cpSync('native/assets', path.join(output,'assets'), {recursive:true});
fs.cpSync('public/art', path.join(output,'art'), {recursive:true});
fs.mkdirSync(path.join(output,'licenses'),{recursive:true});
fs.copyFileSync(path.join(vendor,'LICENSE'),path.join(output,'licenses/raylib.txt'));
fs.copyFileSync('native/vendor/json.hpp',path.join(output,'licenses/nlohmann-json.hpp'));
const nodeLicense=path.join(path.dirname(process.execPath),'LICENSE');
if(fs.existsSync(nodeLicense))fs.copyFileSync(nodeLicense,path.join(output,'licenses/Node.txt'));
const mingwLicense='native/vendor/w64devkit/COPYING.MinGW-w64-runtime.txt';
if(fs.existsSync(mingwLicense))fs.copyFileSync(mingwLicense,path.join(output,'licenses/MinGW-runtime.txt'));
if(fs.existsSync('README.md'))fs.copyFileSync('README.md',path.join(output,'README.md'));
if(fs.existsSync('native/ASSETS.md'))fs.copyFileSync('native/ASSETS.md',path.join(output,'licenses/ASSETS.md'));
const portable = path.join(root,'native/vendor/w64devkit/bin/g++.exe');
const compiler = process.env.CXX || (fs.existsSync(portable) ? portable : 'g++');
const result = spawnSync(compiler, ['-std=c++20','-O2','-static','-I'+path.join(vendor,'include'),'native/main.cpp',path.join(vendor,'lib/libraylib.a'),'-lopengl32','-lgdi32','-lwinmm','-o',path.join(output,'Battlegrounds.exe'),'-mwindows'], {stdio:'inherit',windowsHide:true});
if(result.error) throw result.error;
if(result.status) process.exit(result.status);
console.log('Native app built: '+path.join(output,'Battlegrounds.exe'));
