import {spawn} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
const executable=path.resolve('release/native/Battlegrounds.exe');
if(!fs.existsSync(executable))throw Error('Build the native app first: npm run build');
const smoke=process.argv.includes('--smoke');
const env={...process.env};
if(smoke)env.BOBS_DATA_DIR=path.resolve('test-results/native-smoke-'+Date.now());
const child=spawn(executable,smoke?['--smoke']:[],{env,windowsHide:smoke,stdio:'inherit'});
child.on('error',e=>{console.error(e);process.exit(1);});
child.on('exit',code=>{if(smoke){const result=JSON.parse(fs.readFileSync('release/native/smoke-result.json','utf8'));console.log(result);if(!result.ok)process.exit(1);}process.exit(code??1);});
